name: Generate coverage on CI
on:
  pull_request:
    branches: [ main, next, '*.x' ]
  push:
    branches: [ main, next, '*.x' ]
jobs:
  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm test:cov
      - uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8