name: Release
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Check release instead of publishing'
        default: "false"
        required: false
permissions:
  contents: write
  id-token: write
jobs:
  release:
    name: Generate a new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: ${{ github.event.inputs.dry-run }}
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
          semantic_version: 25